version: '3'
services:
  post-service:
    depends_on: 
      - user-service
    build: ../../
    command: "go run ./micro-service/hal/post/server"
    environment: 
     - USER_SERVICE=http://host.docker.internal:4001
     - RATING_SERVICE=http://host.docker.internal:4003
    ports:
    - "4002:4002"
  user-service:
    build: ../../
    command: "go run ./micro-service/hal/user/server"
    environment: 
     - POST_SERVICE=http://host.docker.internal:4002
    ports:
    - "4001:4001"
  rating-service:
    depends_on: 
      - post-service
    build: ../../
    command: "go run ./micro-service/hal/rating/server"
    environment: 
     - POST_SERVICE=http://host.docker.internal:4002
    ports:
    - "4003:4003"
  # facade-service:
  #   depends_on: 
  #     - post-service
  #     - user-service
  #     - rating-service
  #   build: ../../
  #   command: "go run ./micro-service/hal/facade/server"
  #   environment: 
  #    - POST_SERVICE=http://host.docker.internal:4002
  #    - USER_SERVICE=http://host.docker.internal:4001
  #    - RATING_SERVICE=http://host.docker.internal:4003
  #   ports:
  #    - "4000:4000"

  seed:
    depends_on: 
      - post-service
      - user-service
      - rating-service
    build: ../../
    command: "go run ./micro-service/hal/seed"
    environment: 
     - POST_SERVICE=http://host.docker.internal:4002
     - USER_SERVICE=http://host.docker.internal:4001
     - RATING_SERVICE=http://host.docker.internal:4003
  client:
    depends_on: 
      - seed
    build: ../../
    command: "go run ./micro-service/hal/client"
    environment: 
     - POST_SERVICE=http://host.docker.internal:4002
     - USER_SERVICE=http://host.docker.internal:4001
     - RATING_SERVICE=http://host.docker.internal:4003
  # client-facade:
  #   depends_on: 
  #     - seed
  #   build: ../../
  #   command: "go run ./micro-service/hal/client-facade"
  #   environment: 
  #    - FACADE_SERVICE=facade-service:4000