version: '3'
services:
  post-service:
    depends_on: 
      - user-service
    build: ../../
    command: "go run ./micro-service/grpc/post/server"
    environment: 
     - USER_SERVICE=user-service:50052
    ports:
    - "50051:50051"
  user-service:
    build: ../../
    command: "go run ./micro-service/grpc/user/server"
    ports:
    - "50052:50052"
  rating-service:
    depends_on: 
      - post-service
    build: ../../
    command: "go run ./micro-service/grpc/rating/server"
    environment: 
     - POST_SERVICE=post-service:50051
    ports:
    - "50053:50053"
  facade-service:
    depends_on: 
      - post-service
      - user-service
      - rating-service
    build: ../../
    command: "go run ./micro-service/grpc/facade/server"
    environment: 
     - POST_SERVICE=post-service:50051
     - USER_SERVICE=user-service:50052
     - RATING_SERVICE=rating-service:50053
    ports:
     - "50060:50060"

  seed:
    depends_on: 
      - post-service
      - user-service
      - rating-service
    build: ../../
    command: "go run ./micro-service/grpc/seed"
    environment: 
     - POST_SERVICE=post-service:50051
     - USER_SERVICE=user-service:50052
     - RATING_SERVICE=rating-service:50053

  client:
    depends_on: 
      - seed
    build: ../../
    command: "go run ./micro-service/grpc/client"
    environment: 
     - POST_SERVICE=post-service:50051
     - USER_SERVICE=user-service:50052
     - RATING_SERVICE=rating-service:50053
  client-facade:
    depends_on: 
      - seed
    build: ../../
    command: "go run ./micro-service/grpc/client-facade"
    environment: 
     - FACADE_SERVICE=facade-service:50060